apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.image.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      {{- if .podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .podAntiAffinity.weight }}
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "app.selectorLabels" $ | nindent 20 }}
                topologyKey: {{ .podAntiAffinity.topologyKey }}
      {{- end }}
      {{- end }}
      {{- with .Values.image.volumes }}
      volumes:
        {{- range . }}
        - name: {{ .name }}
          {{- if eq .volumeType "emptyDir" }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.securityContext }}
          securityContext:
            runAsNonRoot: {{ .runAsNonRoot }}
            runAsUser: {{ .runAsUser }}
            allowPrivilegeEscalation: {{ .allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .readOnlyRootFilesystem }}
          {{- end }}
          {{- with .Values.image.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.image.volumes }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.image.startupProbe }}
          startupProbe:
            httpGet:
              port: {{ $.Values.service.targetPort }}
              path: {{ .path }}
              scheme: HTTP
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          readinessProbe:
            httpGet:
              port: {{ .Values.service.targetPort }}
              path: {{ .Values.image.readinessProbe.path }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.image.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.image.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.image.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.image.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.image.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              port: {{ .Values.service.targetPort }}
              path: {{ .Values.image.livenessProbe.path }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.image.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.image.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.image.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.image.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.image.livenessProbe.successThreshold }}
        - name: {{ .Values.metrics.image.name }}
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          {{- with .Values.metrics.image.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.metrics.service.name }}
              containerPort: {{ .Values.metrics.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}